### ISSUE TITLE
Component - Footer

### ISSUE THREAD

**Issue by JalalToufik** [JalalToufik/INK-lets-jam-webapplicatie#17]
**1. Is het component responsive en voldoet het aan de huisstijl?**

- [ ] Ja, hij is volledig responsive

- [x] Voor responsive moet er nog wat gebeuren. Nog niet op alle apparaten getest

- [x] Kan nog een breakpoint worden toegevoegd voor M-scherm

- [ ] Small screen doet het

**2. Voldoet het component aan de coding standards?**

- [ ] Ja
- [x] Nee

**3. Is het component toegankelijk?**

- [x]  Ja, geen bijzonderheden
- [x]  tab test gedaan
- [x]  Light house
- [ ]   Nee, moet nog testen

**4.Is het component performant?**

- [x]  Ja, geen bijzonderheden
- [ ]  Alle plaatjes moeten nog worden toegevoegd en geoptimaliseerd
- [ ]  Image sizes staan in de HTML in de template
- [ ]  loading="lazy" staat in de HTML
- [ ]  Nee, moet nog testen

**Comment by anoukbruinn** [comment]
- De code komt waarschijnlijk niet overheen met het component van de footer die ik heb gemaakt, hij werkt in mijn repo wel responsive maar op de gezamelijk website nog niet, hier moet dus nog wat aan gebeuren.
- ipad doet de button het nog niet goed 
- alle links werken verder in de footer en kunnen zo verder worden gebruikt. 
- waar echt nog aan gewerkt moet worden is de responsive
-
