### ISSUE TITLE
Component - Formulier [8]

### ISSUE THREAD

**Issue by JalalToufik** [JalalToufik/INK-lets-jam-webapplicatie#18]
**1. Is het component responsive en voldoet het aan de huisstijl?**

- [x] Ja, hij is volledig responsive

- [ ] Voor responsive moet er nog wat gebeuren. Nog niet op alle apparaten getest

- [ ] Kan nog een breakpoint worden toegevoegd voor M-scherm

- [ ] Small screen doet het

**2. Voldoet het component aan de coding standards?**

- [x] Ja
- [ ] Nee

**3. Is het component toegankelijk?**

- [ ]  Ja, geen bijzonderheden
- [x]  tab test gedaan
- [x]  Light house
- [ ]   Nee, moet nog testen

**4.Is het component performant?**

- [x]  Ja, geen bijzonderheden
- [ ]  Alle plaatjes moeten nog worden toegevoegd en geoptimaliseerd
- [ ]  Image sizes staan in de HTML in de template
- [ ]  loading="lazy" staat in de HTML
- [ ]  Nee, moet nog testen

**Comment by fatihg61** [comment]
### Wat moet er gebeuren voor de Release Candidate

- Enhancement: Animatie progress bar (Could Have)
- Enhancement: modern flat look (Could Have)

**Comment by fatihg61** [comment]
Ik zou graag feedback willen op de design van mijn component. https://back-to-static-creative-coding-livid.vercel.app/payment

**Comment by fatihg61** [comment]
Kaan Kalmioglu: Je formulier is te groot voor de content dat je erin hebt, verklein de box waar je form inzit, daarnaast ik zou kijken of je die INK logo verkleind links boven kan zetten miss ziet dat er beter uit.

**Comment by fatihg61** [comment]
Formulier in ze geheel heb ik expres groter gemaakt dan normaal wegens dat het de enige component is binnen de website. Het is trekt genoeg aandacht en maakt het fijner voor de end user die niet veel op internet surft snel te kunnen betalen!

**Comment by JalalToufik** [comment]
formulier zit er in
