### ISSUE TITLE
Component - BecomeSponsor [7]

### ISSUE THREAD

**Issue by JalalToufik** [JalalToufik/INK-lets-jam-webapplicatie#21]
**1. Is het component responsive en voldoet het aan de huisstijl?**

- [ ] Ja, hij is volledig responsive

- [x] Voor responsive moet er nog wat gebeuren. Nog niet op alle apparaten getest

- [ ] Kan nog een breakpoint worden toegevoegd voor M-scherm

- [ ] Small screen doet het

**2. Voldoet het component aan de coding standards?**

- [x] Ja
- [ ] Nee

**3. Is het component toegankelijk?**

- [ ]  Ja, geen bijzonderheden
- [x]  tab test gedaan
- [x]  Light house
- [ ]   Nee, moet nog testen

**4.Is het component performant?**

- [x]  Ja, geen bijzonderheden
- [ ]  Alle plaatjes moeten nog worden toegevoegd en geoptimaliseerd
- [ ]  Image sizes staan in de HTML in de template
- [ ]  loading="lazy" staat in de HTML
- [ ]  Nee, moet nog testen

**Comment by fatihg61** [comment]
### Wat moet er gebeuren voor de Release Candidate

- Responsive: Tablet versie verbeteren. Is niet responsive (Must Have)

**Comment by fatihg61** [comment]
Ik zou graag feedback willen op performance en toegankelijkheid van mijn component. https://back-to-static-creative-coding-livid.vercel.app

**Comment by fatihg61** [comment]
Kaan Kalmioglu: 
Performance: t laad snel in, werkt smooth mee ook bij het resizen van je window laad het smooth en snel.
Toegankelijkheid: Je kan lekker tabben en de score is ook hoog. Alleen ik zou wel het contrast checken van wit op blauw.

**Comment by fatihg61** [comment]
Ik kan doormiddel van contrast checker een betere kleur kunnen kiezen voor de button. Alleen de kleur verandert alleen bij een hover. In een real life scenario zou het niet veel uitmaken en buiten moet ik dan ook de keuze maken om af te wijken van de huis style wat onze opdrachgever totaal niet wilt.

**Comment by JalalToufik** [comment]
Component is afgerond met nieuwe svg.
