### ISSUE TITLE
Heb je dit echt nog nodig?

### ISSUE THREAD

**Issue by KrijnHoetmer** [JalalToufik/INK-lets-jam-webapplicatie#28]
Volgens mij sinds 2012 niet meer :)

https://github.com/JalalToufik/INK-lets-jam-webapplicatie/blob/c7a3ffa14ba4614970b808c8da2389c71038193a/src/lib/organisms/MainStory.svelte#L104C15-L107

**Comment by JalalToufik** [comment]
Geen idee denk het niet :p
